-- This file can be loaded by calling `lua require('plugins')` from your init.vim

local ensure_packer = function()
    local fn = vim.fn
    local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
    if fn.empty(fn.glob(install_path)) > 0 then
        fn.system({ "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path })
        vim.cmd([[packadd packer.nvim]])
        return true
    end
    return false
end

local packer_bootstrap = ensure_packer()

return require("packer").startup({
    function(use)
        -- Packer can manage itself
        use("wbthomason/packer.nvim")

        use({ "tweekmonster/startuptime.vim", opt = true, cmd = { "StartupTime" } })
        use("tpope/vim-fugitive")
        use({
            "scrooloose/nerdcommenter",
            config = function()
                -- Comment with one Space
                vim.g.NERDSpaceDelims = 1
            end,
        })
        use("terryma/vim-multiple-cursors")
        use("tpope/vim-surround")
        use("tpope/vim-repeat")
        use({ "leafgarland/typescript-vim", opt = true, ft = { "typescript" } })
        use({ "posva/vim-vue", opt = true, ft = { "vue" } })
        use({
            "junegunn/vim-easy-align",
            config = function()
                -- Start interactive EasyAlign in visual mode (e.g. vipga)
                -- Start interactive EasyAlign for a motion/text object (e.g. gaip)
                vim.keymap.set({ "x", "n" }, "ga", "<Plug>(EasyAlign)")
            end,
        })
        use("patstockwell/vim-monokai-tasty")
        use({ "Yggdroot/indentLine", config = function() vim.g.indentLine_char = "⎸" end })
        -- select and press gr
        use("vim-scripts/ReplaceWithRegister")
        -- Execute linux cmd in vim :SudoWrite, :SudoEdit, :Mkdirr etc.
        use({
            "tpope/vim-eunuch",
            opt = true,
            cmd = {
                "Remove",
                "Delete",
                "Move",
                "Chmod",
                "Mkdir",
                "Cfind",
                "Clocate",
                "Lfind",
                "Llocate",
                "Wall",
                "SudoWrite",
                "SudoEdit",
            },
        })
        --  ']' and '[' mappings
        --  '[e', ']e' exchange lines, '[<space>', ']<space>' add blank lines, etc.
        --  '[l', ']l' jump between warnings generated by lint tools
        use("tpope/vim-unimpaired")
        --  Automatically clears search highlight when cursor is moved
        --  Improved star-search (visual-mode, highlighting without moving)
        use("junegunn/vim-slash")
        use("godlygeek/tabular")
        -- calcuate programming time
        use("wakatime/vim-wakatime")
        -- cx{range} to swap two text-obj, X for select mode
        use("tommcdo/vim-exchange")
        use("machakann/vim-highlightedyank")
        use("vim-scripts/argtextobj.vim")
        -- toggle quickfix list with <learder>q and toggle location list with <leader>l
        use("Valloric/ListToggle")
        -- + expand_region_expand
        -- _ expand_region_shrink
        use("terryma/vim-expand-region")
        -- Browsing the files
        use("justinmk/vim-dirvish")
        -- lots of languages syntax highlighting support
        use("sheerun/vim-polyglot")
        use({
            "vim-scripts/taglist.vim",
            config = function() vim.keymap.set("", "<F2>", ":TlistToggle<CR>", { noremap = true }) end,
        })
        use({
            "honza/vim-snippets",
            {
                "SirVer/ultisnips",
                config = function()
                    vim.g.UltiSnipsJumpForwardTrigger = "<c-b>"
                    vim.g.UltiSnipsJumpBackwardTrigger = "<c-z>"
                end,
            },
        })
        use({ "mattn/emmet-vim", config = function() vim.g.user_emmet_leader_key = "<C-j>" end })
        use({
            "jiangmiao/auto-pairs",
            config = function()
                vim.g.AutoPairsShortcutToggle = ""
                vim.g.AutoPairsFlyMode = 0
            end,
        })
        use({
            "vim-scripts/groovy.vim",
            {
                "vim-scripts/groovyindent-unix",
                config = function() vim.api.nvim_create_autocmd("Filetype", { pattern = "groovy", command = "setlocal sw=2" }) end,
            },
        })
        use({
            "easymotion/vim-easymotion",
            config = function()
                vim.g.EasyMotion_do_mapping = 0 -- Disable default mappings
                -- <space>s{char}{char} to move to {char}{char}
                vim.keymap.set("n", "<space>s", "<Plug>(easymotion-overwin-f2)")
                -- <space>f{char} to move to {char}
                vim.keymap.set({ "", "n" }, "<space>f", "<Plug>(easymotion-overwin-f)")
                -- Move to line
                vim.keymap.set({ "", "n" }, "<space>L", "<Plug>(easymotion-overwin-line)")
                -- Move to word
                vim.keymap.set({ "", "n" }, "<space>w", "<Plug>(easymotion-overwin-w)")
                -- Turn on case insensitive feature
                vim.g.EasyMotion_smartcase = 1
                -- JK motions: Line motions
                vim.keymap.set("", "<space>j", "<Plug>(easymotion-j)")
                vim.keymap.set("", "<space>k", "<Plug>(easymotion-k)")
            end,
        })
        use({
            "plasticboy/vim-markdown",
            opt = true,
            ft = { "markdown" },
            config = function()
                vim.g.vim_markdown_new_list_item_indent = 2
                vim.g.vim_markdown_toc_autofit = 1
                --  Show the link url explicitly
                vim.g.vim_markdown_conceal = 0
                --  Show the code block symbol explicitly
                vim.g.vim_markdown_conceal_code_blocks = 0
                -- markdown-setting: YAML
                vim.g.vim_markdown_frontmatter = 1
            end,
        })

        -- replace the filetype.vim for speeding up
        -- Do not source the default filetype.vim
        use({ "nathom/filetype.nvim", config = function() vim.g.did_load_filetypes = 1 end })

        -- Lazy loading:
        -- Load on specific commands
        use({ "tpope/vim-dispatch", opt = true, cmd = { "Dispatch", "Make", "Focus", "Start" } })

        -- Load on an autocommand event
        use({ "andymass/vim-matchup", event = "VimEnter" })

        -- Use dependency and run lua function after load
        use({
            "lewis6991/gitsigns.nvim",
            requires = { "nvim-lua/plenary.nvim" },
            config = function() require("gitsigns").setup(require("plugins.gitsigns")) end,
        })

        -- You can specify multiple plugins in a single call
        use({
            "nvim-treesitter/nvim-treesitter",
            run = ":TSUpdate",
            config = function()
                require("nvim-treesitter.configs").setup({
                    ensure_installed = { "lua", "cmake", "vim", "bash", "toml", "yaml" },
                    highlight = {
                        enable = true,
                        additional_vim_regex_highlighting = false,
                        disable = function(lang, buf)
                            local max_filesize = 100 * 1024 -- 100 KB
                            local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
                            if ok and stats and stats.size > max_filesize then
                                return true
                            end
                        end,
                    },
                    indent = { enable = true },
                    incremental_selection = {
                        enable = true,
                        keymaps = {
                            init_selection = "<CR>",
                            node_incremental = "<CR>",
                            node_decremental = "<BS>",
                            scope_incremental = "<TAB>",
                        },
                    },
                })

                vim.o.foldmethod = "expr"
                vim.o.foldexpr = "nvim_treesitter#foldexpr()"
            end,
        })

        use({
            "fgheng/winbar.nvim",
            config = function()
                require("winbar").setup({
                    enabled = true,

                    show_file_path = true,
                    show_symbols = true,

                    colors = {
                        path = "", -- You can customize colors like #c946fd
                        file_name = "",
                        symbols = "",
                    },

                    icons = {
                        file_icon_default = "",
                        seperator = ">",
                        editor_state = "●",
                        lock_icon = "",
                    },

                    exclude_filetype = {
                        "help",
                        "startify",
                        "dashboard",
                        "packer",
                        "neogitstatus",
                        "NvimTree",
                        "Trouble",
                        "alpha",
                        "lir",
                        "Outline",
                        "spectre_panel",
                        "toggleterm",
                        "qf",
                    },
                })
            end,
        })

        -- replace nerdtree
        use({
            "nvim-tree/nvim-tree.lua",
            requires = { "nvim-tree/nvim-web-devicons" },
            opt = true,
            cmd = { "NvimTreeToggle" },
            keys = { "<F3>" },
            tag = "nightly", -- optional, updated every week. (see issue #1193)
            config = function()
                require("nvim-tree").setup()
                vim.keymap.set("", "<F3>", "<Cmd> :NvimTreeToggle<CR>")
            end,
        })

        -- hirechercy like pycharm
        use({
            "simrat39/symbols-outline.nvim",
            opt = true,
            cmd = { "SymbolsOutlineOpen", "SymbolsOutline" },
            config = function()
                require("symbols-outline").setup({
                    highlight_hovered_item = true,
                    show_guides = true,
                    auto_preview = false,
                    position = "right",
                    relative_width = true,
                    width = 25,
                    auto_close = false,
                    show_numbers = false,
                    show_relative_numbers = false,
                    show_symbol_details = true,
                    preview_bg_highlight = "Pmenu",
                    autofold_depth = nil,
                    auto_unfold_hover = true,
                    fold_markers = { "", "" },
                    wrap = false,
                    keymaps = { -- These keymaps can be a string or a table for multiple keys
                        close = { "<Esc>", "q" },
                        goto_location = "<Cr>",
                        focus_location = "o",
                        hover_symbol = "<C-space>",
                        toggle_preview = "K",
                        rename_symbol = "r",
                        code_actions = "a",
                        fold = "h",
                        unfold = "l",
                        fold_all = "W",
                        unfold_all = "E",
                        fold_reset = "R",
                    },
                    lsp_blacklist = {},
                    symbol_blacklist = {},
                    symbols = {
                        -- File = { icon = "����", hl = "TSURI" },
                        Module = { icon = "", hl = "TSNamespace" },
                        Namespace = { icon = "", hl = "TSNamespace" },
                        Package = { icon = "", hl = "TSNamespace" },
                        Class = { icon = "𝓒", hl = "TSType" },
                        Method = { icon = "ƒ", hl = "TSMethod" },
                        Property = { icon = "", hl = "TSMethod" },
                        Field = { icon = "", hl = "TSField" },
                        Constructor = { icon = "", hl = "TSConstructor" },
                        Enum = { icon = "ℰ", hl = "TSType" },
                        Interface = { icon = "ﰮ", hl = "TSType" },
                        Function = { icon = "", hl = "TSFunction" },
                        Variable = { icon = "", hl = "TSConstant" },
                        Constant = { icon = "", hl = "TSConstant" },
                        String = { icon = "𝓐", hl = "TSString" },
                        Number = { icon = "#", hl = "TSNumber" },
                        Boolean = { icon = "⊨", hl = "TSBoolean" },
                        Array = { icon = "", hl = "TSConstant" },
                        Object = { icon = "⦿", hl = "TSType" },
                        Key = { icon = "🔐", hl = "TSType" },
                        Null = { icon = "NULL", hl = "TSType" },
                        EnumMember = { icon = "", hl = "TSField" },
                        Struct = { icon = "𝓢", hl = "TSType" },
                        Event = { icon = "🗲", hl = "TSType" },
                        Operator = { icon = "+", hl = "TSOperator" },
                        TypeParameter = { icon = "𝙏", hl = "TSParameter" },
                    },
                })
            end,
        })

        use({
            "folke/todo-comments.nvim",
            requires = "nvim-lua/plenary.nvim",
            config = function() require("todo-comments").setup() end,
        })

        use({
            "folke/trouble.nvim",
            requires = "kyazdani42/nvim-web-devicons",
            opt = true,
            cmd = { "Trouble", "TroubleToggle" },
            config = function() require("trouble").setup() end,
        })

        use({ "lewis6991/impatient.nvim", config = function() require("impatient") end })

        use({ "neoclide/coc.nvim", branch = "release", config = function() require("plugins.coc") end })

        use({
            "nvim-lualine/lualine.nvim",
            requires = { "kyazdani42/nvim-web-devicons", opt = true },
            config = function()
                require("lualine").setup({
                    options = { globalstatus = true, theme = "horizon" },
                    extensions = { "fzf", "nvim-tree", "symbols-outline", "fugitive" },
                    sections = {
                        lualine_b = {
                            "branch",
                            "diff",
                            {
                                "diagnostics",
                                -- Table of diagnostic sources, available sources are:
                                --   'nvim_lsp', 'nvim_diagnostic', 'nvim_workspace_diagnostic', 'coc', 'ale', 'vim_lsp'.
                                -- or a function that returns a table as such:
                                --   { error=error_cnt, warn=warn_cnt, info=info_cnt, hint=hint_cnt }
                                sources = { "nvim_diagnostic", "ale", "coc" },
                            },
                        },
                        lualine_c = { "windows" },
                    },
                })
            end,
        })

        vim.api.nvim_create_augroup("packer_auto_compile", {})
        vim.api.nvim_create_autocmd("BufWritePost", {
            group = "packer_auto_compile",
            command = "source <afile> | PackerCompile",
            pattern = "*/nvim/lua/plugins/*.lua",
        })

        -- Automatically set up your configuration after cloning packer.nvim
        -- Put this at the end after all plugins
        if packer_bootstrap then
            require("packer").sync()
        end
    end,
    config = {
        display = {
            open_fn = function()
                local result, win, buf = require("packer.util").float({
                    border = {
                        { "╭", "FloatBorder" },
                        { "─", "FloatBorder" },
                        { "╮", "FloatBorder" },
                        { "│", "FloatBorder" },
                        { "╯", "FloatBorder" },
                        { "─", "FloatBorder" },
                        { "╰", "FloatBorder" },
                        { "│", "FloatBorder" },
                    },
                })
                vim.api.nvim_win_set_option(win, "winhighlight", "NormalFloat:Normal")
                return result, win, buf
            end,
        },
    },
})
